services:

  portainer:
    image: portainer/portainer-ce:2.26.1
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data/
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.portainer.rule=Host(`portainer.my.home.com`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - traefik-proxy

volumes:
  portainer-data:

networks:
  traefik-proxy:
    external: true
